### ISSUE TITLE
setPreSendingHandler not appending data to instabug report

### ISSUE THREAD

**Issue by sebirdman** [Instabug/instabug-reactnative#88]
I'm not sure if this is by design, the documentation says:

> This block is executed in the background before sending each report. Could be used for attaching logs and extra data to reports.

```
        Instabug.setPreSendingHandler(() => {
            Instabug.setUserAttribute("TEST", "my test");
            Instabug.logUserEventWithNameAndParams("OnFeedbackButtonClicked","params");
        });
```

Neither the user attribute, nor the userEvent seem to be logged.

**Comment by reemalashry1** [comment]
Hey @sebirdman 
I apologize as there's a fault in the docs, we will edit it right away, to use the user events with the `PreSendingHandler` you need to write this instead: `Instabug.logUserEventWithNameAndParams("OnFeedbackButtonClicked",{"key": "value"}); `
With the key and value as the user events parameters.

However we seem to have an issue with using the user events with `setPreSendingHandler`, we are currently looking into it, I'll get back to you about it.

For the user attributes, please note that they appear with the bug's data above the logs part, just like it's explained [here](https://docs.instabug.com/docs/ios-identify-user#section-user-attributes)

**Comment by reemalashry1** [comment]
Hey @sebirdman we have fixed the issue with the user events with `setPreSendingHandler`
Please install using 
`npm install https://github.com/Instabug/instabug-reactnative#customBuild/fix_loguserevents_with_presendinghandler`

**Comment by sebirdman** [comment]
Hi @reemalashry1 i'm still seeing this issue with that branch and the following code:

```
         console.log("Adding Presending handler")
         Instabug.setPreSendingHandler(() => {
                console.log("PRE EVENT TRIGGERED");
                Instabug.logUserEventWithNameAndParams("OnFeedbackButtonClicked", { key: "value" });
            });
```

i see the "adding presending handler" log, but do not see the event name or the console.log inside the handler. 

Let me know if you need more information.

**Comment by reemalashry1** [comment]
Hey @sebirdman we have an issue to show user events and console logs on the dashboard, we are working on it, will keep you updated :)

**Comment by ZiadAyman** [comment]
Hey @sebirdman we fixed both issues. You can log user events now and everything would be working perfectly. 
Regarding the console logs, we made a SNAPSHOT for you that includes the fix of the console logs inside the Pre sending handler. Kindly use  4.3.3.8-SNAPSHOT. 

Thanks for your patience :)

**Comment by ZiadAyman** [comment]
hey @sebirdman 

Here is the react-native branch with the native custom build that has the fix on. Apologies for delivering it late! "https://github.com/Instabug/instabug-reactnative#customBuild/fix_loguserevents_with_presendinghandler"

Please don't hesitate to share here your updates and let me know if there is anything else we need to do from our side :)

**Comment by jonahkagan** [comment]
I'm also running into this issue using the latest instabug-reactnative (v2.0.18) on ios. I can't seem to get any user events or logs to show up whether I put them in the presending handler or not. Can you please elaborate on what you fixed and whether the fix is deployed? Thanks!

**Comment by ZiadAyman** [comment]
Hey @jonahkagan We had a problem with logging the user events, we fixed it and yes it's tested and deployed.  As for logging console logs inside `presending handler`, it's fixed in 4.3.3.8-SNAPSHOT for native android and in this branch [branch](https://github.com/Instabug/instabug-reactnative#customBuild/fix_loguserevents_with_presendinghandler) for react-native.

Can you tell please if you are not able to get any logs in general on your dashboard? I mean you fail to get instabug logs, console logs and network logs?

**Comment by jonahkagan** [comment]
I get logs in general on my dashboard. I don't get logs from inside the presending handler (which makes sense since I wasn't using that custom branch).

There are two other issues I'm having that don't seem to have been addressed:
1. I don't get logs from my application code (e.g. from lifecycle methods on my React components). I only see logs from library code.
2. I don't see any user events recorded. I tried both from a presending handler and from React component lifecycle methods. Do I need to use the custom branch you mentioned in order to log user events?

I've found another workaround to get access to the user data I need, so I'm no longer blocked by this.

**Comment by ZiadAyman** [comment]
@jonahkagan I communicated the issue for the logs from your application code as well as the user events problem and will get back to you with updates :)

**Comment by ZiadAyman** [comment]
Hey @jonahkagan 

After checking it seems that logs are working fine in React Native's life cycle methods. You might only face a problem if you are trying to attach console logs inside the constructor of your component. If you are trying to log inside your constructor so you can use for now instabug logs. This will solve the issue for now :)

Also, do you mind clarifying what do you mean by getting logs only from your library code?

As for the user events, we are currently investigating the issue and I'll get back to you whenever everything is good. 

Did I answer your questions?

**Comment by ZiadAyman** [comment]
hey @jonahkagan I have another question for you please. 

Are you facing a problem with receiving the user events on your dashboard in the bug page or within the users page?

**Comment by sebirdman** [comment]
@ZiadAyman sorry to get back to you so late. 

with the updated changes i'm seeing the events! thanks for all the help.

**Comment by ZiadAyman** [comment]
@sebirdman Perfect. You can use the branch also for attaching logs inside the `presending handler` and I will notify you here once it's included officially in our `react-native` release. Should take few days from now.

**Comment by jonahkagan** [comment]
I'm seeing the console logs now. Thanks
